- composer.json
Although the original ticket recommended increasing our
minimum-stability, this change gives us the best of both worlds.
- Where stable packages are available and meet the requirements, they
will be used.
- Where stable packages aren’t available or they don’t meet the
dependency requirements, non-stable packages are still allowed.
As part of this I have also tightened up the silverstripe-themes req
version, as `*` is an anti-pattern. The versioning of the theme has
rightly split off from the versioning of the framework; it looks like
3.1.* is what we should expect.
Arguably, we could set the dependency to ~3.1, but in this case I think
it’s fine to be conservative.
> Prefer stable packages while still allowing dev ones. Fixes #100

- composer.json
php-tidy is required to run the test suite.
> Require php-tidy for dev dependencies

- composer.json
This reverts commit bb24a9192eef39070b010520003f6ff10c6521f0.
Fixes https://github.com/silverstripe/silverstripe-installer/issues/120
> Revert "Require php-tidy for dev dependencies (#87)"

- mysite/_config/config.yml
Enable https://github.com/silverstripe/silverstripe-framework/pull/5556 by default for new projects
> API Enable friendly error HTTP code by default for new projects

- CONTRIBUTING.md
Make the notice here match those on other modules.
See https://github.com/silverstripe/silverstripe-framework/pull/5610
> Make installer copyright note conform to others

- composer.json
* Resolves #131 
Unless there's a reason for keeping `^1`! :)
> FIX use latest dev-master for asset-admin composer contraint

- mysite/_config.php
It's not necessary; i18n default_locale is already `en_US` and we want to make this file redundant anyway at some point.
> Remove i18n::set_locale from default installer

- assets/.htaccess
Need to escape these slashes since they were resulting in unescaped `.` in the htaccess regex.
Merge with https://github.com/silverstripe/silverstripe-framework/pull/6061
> BUG Fix incorrect backslash escaping in htaccess template

- composer.json
This is required here in order for the "cow" release tool
to include the module in tagging releases.
At the moment, it's only an indirect asset-admin dependency,
but will become a framework dependency once we switch
CampaignAdmin to use GraphQL as well.
Merge after https://github.com/silverstripe/silverstripe-asset-admin/pull/368
> Added GraphQL dependency

- .htaccess
If you're running mod_dir on Apache, and create a route which matches a directory name
(such as 'framework'), "GET /framework" will result in a 301 to "/framework/?url=framework".
While the SilverStripe routing might decide to enforce trailing slash rules later,
Apache shouldn't have any business here.
The specific bug this fixes was redirecting "/graphql" to "/graphql/",
with the silverstripe/graphql module installed.
See https://httpd.apache.org/docs/current/mod/mod_dir.html#directoryslash
> Disable trailing slash redirect for dirs

- .htaccess
I've seen it happen quiet frequently that error logs are located in the web root or `Debug::log()` statements where forgotten and deployed to live.
I think disallowing the most common file names here would limit the potential of accidentally exposing sensitive information drastically (especially because the `Debug::log()` file name or location can not be configured).
> Block common log file names in .htaccess

- .editorconfig
- composer.json
See https://github.com/silverstripe/silverstripe-framework/pull/6725
Additionally rebased on top of https://github.com/silverstripe/silverstripe-installer/pull/158
Sorted dependencies by name and bumped up min php version to 5.6
> Add assets / versioned modules

- .editorconfig
- index.php
- install.php
- mysite/_config.php
- mysite/code/Page.php
- mysite/code/Page_Controller.php
- phpcs.xml.dist
**Note:** I've raised this PR against 3.4 because I think we should add this for all currently supported versions of SS 3.x.
---
This ruleset is based on PSR-2, but excludes the following rules:
* Classes must have a namespace
* Classes must be in a file of their own
* Spaces for indentation (prefer tabs)
* Method naming must be camelCase and class names must be StudlyCase (underscores break both  of these)
It will exclude the vendor and thirdparty directories it finds if running over a project, as well as the index.php file (we may want to exclude framework/main.php too?).
Issue: https://github.com/silverstripe/silverstripe-framework/issues/6643
---
Couple of things for discussion:
* While linting supported modules to adhere to these standards, should we just bite the bullet and convert …
> Add PHPCS standard for SS 3.x

- .gitignore
composer will maintain these folders for us, ignore just like the vendor folder.
I debated a bit on the themes/simple folder, but if people are going to modify it then they will get warnings / over-written when new updates happen...~
> Add in the module folders which come from the default install

- .gitattributes
The “export” downloads of the installer should include these two files
as they are of use to regular developers.
* .editorconfig encourages the use of our standard code format
* .env.example is a helper for new developers
> FIX: Include .env.example and .editorconfig in git export

- assets/.gitignore
Duplicated from #212 as I'm told pull requests to 3.5 will get merged into 4.x eventually.
Uploading files directly through the Files LeftAndMain drops them directly into the assets folder by default. This will help prevent those files accidentally ending up in git.
> Ignore (almost) everything in the assets folder

- composer.json
SS 3.x supports PHP 7 so we need to allow a range of PHPUnit versions
> Update phpunit deps to match framework

- composer.json
These files to not always exist in this path, so this autoload definition is misleading
For example, if a project requires the installer recipe then it gets installed into vendor/silverstripe/installer, so this classmap is very wrong - the files belong to the silverstripe/recipe-cms recipe so should be loaded there if anywhere
> FIX Remove incorrect classmap for Page and PageController

- composer.json
Add Security Advisories as dev requirement to
- Prevent installation of known breached libraries
- Give devs the option to remove it if they might want to
Related: silverstripe/silverstripe-framework#8548
> Add Roave Security advisories to composer

- .gitignore
- composer.json
Make `_resources` the default location for vendor-expose in 4.4
* https://github.com/silverstripe/silverstripe-framework/issues/7932
> MINOR Make installer default to using `_resources`

- .travis.yml
Most of the modules stop exporting metadata files (behat.yml among those) to packagist
Thus when travis runs behat tests it cannot find configuration for the test suites
Fixes #243
> FIX / Installer tests

- .editorconfig
- .travis.yml
- phpunit.xml.dist
Also removed an unneeded editorconfig block which is duplicated and adds PHP 7.2 and 7.3 into the builds
> Split framework tests from assets and versioned to prevent time limits being exceeded

- app/_config/assets.yml
We added some custom file resolution settings to recipe-core that was meant to only go into brand new SS4.4 project. However, we realised this would break the file migration for people upgrading directly from SiverStripe 3 to SilverStripe 4.4. So we're moving it to the installer instead.
> NEW Disable legacy resolution for new projects

- .cow.json
See https://github.com/silverstripe/silverstripe-framework/issues/9232.
This should be merged up to 4.4 and 4.
> Remove cow archive metadata

- .cow/changelog.md.twig
Following the [addition of the full `Version` object](https://github.com/silverstripe/cow/pull/157) to the template handler in Cow, we can apply a specific message to the changelog for RCs.
> DOC Adjust changelog template for RC releases

- README.md
Some older redirects have disappeared with the new documentation site, so I've updated the URLs here. I also tweaked the Installation section to include the base Composer command and to link to Getting Started.
Resolves #269.
> DOC Update README with valid links to documentation

- .env.example
When running a dev/build for the first time, environment should be set to 'dev' or it won't run. 
Setting this in the example gives guidance to someone building a site for the first time (or if it's been ages!)
> Set environment type in example

- .gitattributes
The .cow folder is only useful when doing a release with cow. People don't need it when starting a new project.
* Resolves #287
> BUG Don't include the .cow folders in releases

- .cow/changelog.md.twig
I've taken reference from the [4.6.1 change log](https://github.com/silverstripe/silverstripe-framework/blob/4/docs/en/04_Changelogs/4.6.1.md) to use the 'CMS Recipe' table. 
The other information is taken from the existing CWP change log template, see: https://github.com/silverstripe/cwp-recipe-kitchen-sink/blob/2/.changelog.md.twig
> DOCS more information in changelog template

- web.config
This commit fixes #262.
This commit adds a `web.config`-file to the project's root which redirects all urls to `public/` in order to make SilverStripe & IIS act the same like SilverStripe & Apache.
> Add redirects to `public/` for iis

- .travis.yml
Issue https://github.com/silverstripe/silverstripe-installer/issues/298
Broken job `BEHAT_SUITE=framework` with 'framework snippet undefined' is unrelated and being handled separately on https://github.com/silverstripe/silverstripe-installer/issues/300
> MNT Bump frameworktest

- .travis.yml
Issue https://github.com/silverstripe/silverstripe-installer/issues/300
There are no framework behat tests.  The framework behat setup is a non-standard setup that just calls the admin suite.  I'm not sure what the historic background for why it's like this is, though it just seems like we should just call the admin behat suite directly like we do for everything else.
There's some other unrelated broken tests on the travis build
> MNT Use admin behat suite instead of framework

- composer.json
As of Composer 2.2.0, there is a new configuration property to whitelist plugins which are allowed to run. According to https://getcomposer.org/doc/06-config.md#allow-plugins this will default to disallow all plugins from July 2022.
> ENH Explicitly allow SilverStripe composer plugins

- composer.json
This plugin is always required for silverstripe installs, so we should allow it by default.
- silverstripeltd/product-issues#528
> MNT Add composer/installers to allow-plugins by default.

- .travis.yml
PGSQL tests are failing for no apparent reason, cannot replicate locally
https://app.travis-ci.com/github/silverstripe/silverstripe-installer/jobs/568487613#L1390
We have PGSQL in the shared config, so there's still plenty of times that we're testing the postgres still functions
> MNT Only use mysql in matrix

- composer.json
This directory will be required for all new projects (unless explicitly opting out of graphql v4) - having this directory by default makes it easier to set more sane permissions (i.e. not requiring the entire project root to be writable).
In silverstripe/silverstripe-framework#10339 the docs are being updated to say this is best practice - so this PR gives best practice out-of-the-box.
> ENH Add `.graphql-generated` directory by default
