silverstripe/silverstripe-installer

assets/.htaccess

Fixes silverstripe-framework's issue 3692.

.htaccess: support for MS Office template / macro files

---

.htaccess

FIX Requests to root dir circumvent index.php

---

composer.json

Added phpunit to dev dependencies

---

.htaccess

Re-opened PR for https://github.com/silverstripe/silverstripe-installer/pull/91 against 3.1

Ensure BlockUntrustedProxyHeaders is enabled by default

---

web.config

FIX Invalid comment syntax for web.config

---

assets/.htaccess

This should be combined with a PR I have started on silverstripe-framework https://github.com/silverstripe/silverstripe-framework/pull/4669

Allowing SVGs in the assets directory

---

.gitignore
assets/.gitignore

.gitignore re-organisation

---

composer.json

It's a shame we can't do this against 3.x but OH WELL

Bumping PHPUnit version

---

composer.json

Requires https://github.com/silverstripe/silverstripe-asset-admin/pull/132

API Include asset-admin module in installer

---

composer.json

update required php version

---

mysite/_config/config.yml

To merge with https://github.com/silverstripe/silverstripe-framework/pull/5826

API Support nested themes API

---

mysite/code/Page.php

See https://github.com/silverstripe/silverstripe-cms/issues/1572

Update for CMS namespace

---

install.php
mysite/_config/config.yml
phpunit.xml.dist

Merge with https://github.com/silverstripe/silverstripe-framework/pull/5921

Upgrade installer

---

phpunit.xml.dist

Merge with https://github.com/silverstripe/silverstripe-framework/pull/5974

Rename SS_ prefixed classes

---

composer.json

Lock dev branches to dev
Broken out of https://github.com/silverstripe/silverstripe-installer/pull/137/
Merge with https://github.com/silverstripe-themes/silverstripe-simple/pull/44 since the theme has been changed.

Remove self.version

---

.cow.json
.gitattributes

This will be used to allow better configurability of module releases in the future
In-progress readme at https://github.com/open-sausages/cow/blob/c951b7f000bbccf99ffb72c0d66609cccc8d2414/cow-schema.md

[WIP] Add experimental release metadata to module

---

mysite/code/Page.php
mysite/code/PageController.php

Issue: silverstripe/silverstripe-framework#6403
Blockers:

API Change Page_Controller to PageController (PSR-2 compliance)

---

mysite/code/PageController.php

`Controller` has had it's `init()` method changed to `protected`, updating `PageController` to follow suit.

Changed init() visibility to protected

---

.env.example
.gitignore
.htaccess
web.config

Depends on https://github.com/silverstripe/silverstripe-framework/pull/6337

NEW Add .env.example file

---

mysite/_config/config.yml

This fixes a circular dependency in the default install

Fix remove the wildcard After condition in config.yml

---

composer.json

Requires https://github.com/silverstripe/silverstripe-framework/pull/6695

Add admin module to root installer

---

composer.json

Merge with https://github.com/silverstripe/silverstripe-framework/pull/6712

Fix dev dependencies for root project

---

composer.json

For https://github.com/silverstripe/silverstripe-framework/pull/6723

Add assets as module

---

composer.json

see https://github.com/silverstripe/silverstripe-framework/pull/6736 and https://github.com/silverstripe/silverstripe-framework/pull/6718

Update PHP min version and PHPUnit version

---

composer.json

See https://github.com/silverstripe/silverstripe-framework/issues/6735

Add campaign admin module

---

phpunit.teamcity.mssql.xml
phpunit.xml.dist

Remove reference to deleted TestListener class (see https://github.com/silverstripe/silverstripe-framework/pull/6734)

Update PHPUnit XML configs to remove SS TestListener

---

.cow.json

Fixes https://github.com/silverstripe/silverstripe-framework/issues/6737

Lock dependency-constraint prior to beta

---

behat.yml

See https://github.com/silverstripe/silverstripe-behat-extension/pull/152

Update for behat 3

---

.htaccess

See https://github.com/silverstripe/silverstripe-framework/pull/6798

API Remove BlockUntrustedIPs

---

index.php
install.php
mysite/code/Page.php
mysite/code/PageController.php

Noticed today when started playing with SS4 that the two PHP files in the mysite/code/ where tabs and not spaces.
This PR update spacing and some other small tweaks for PSR-2

Update the PHP files to PSR-2 spec

---

.gitignore
.travis.yml
behat.yml

Closes https://github.com/silverstripe/silverstripe-installer/issues/164

API Add pgsql + behat tests to installer

---

mysite/_config.php

Main issue: https://github.com/silverstripe/silverstripe-framework/issues/6681
See https://github.com/silverstripe/silverstripe-framework/pull/7037 for framework pull request

Remove unneeded globals

---

composer.json

This should only be merged after the following:
* https://github.com/silverstripe/silverstripe-errorpage/pull/2
* https://github.com/silverstripe/silverstripe-framework/pull/7017
* https://github.com/silverstripe/silverstripe-cms/pull/1849

Added errorpage module requirement

---

README.md

Issue: https://github.com/silverstripe/silverstripe-framework/issues/7205

Provide information related to recipe

---

.travis.yml
behat.yml

Fixes https://github.com/silverstripe/silverstripe-installer/issues/192

Adjust behat timeout for asset-admin tests

---

assets/.htaccess
behat.yml
index.php
install-frameworkmissing.html
install.php
phpunit.xml.dist

See https://github.com/silverstripe/silverstripe-framework/issues/7405

Support custom main.php location

---

.gitignore

See https://github.com/silverstripe/silverstripe-framework/issues/7405s

Update gitignore for vendor module move

---

composer.json

Merge with:
- https://github.com/silverstripe/recipe-cms/pull/3
- https://github.com/silverstripe/recipe-core/pull/10

Update recipe-plugin to 1.0

---

composer.json
phpcs.xml.dist
phpunit.xml.dist

DOCS update comments for supported versions

---

.travis.yml

Parent issue: https://github.com/silverstripe/silverstripe-framework/issues/6890

Feature update composer with --prefer-source flag so that tests are included

---

.travis.yml

Step 1 to make travis builds ~great~ green again

FIX travis OS build version so that behat will function

---

.travis.yml

added a test for not adding test modules and using `curl` to see if anything errors
Fixes https://github.com/silverstripe/silverstripe-installer/issues/175

Enhancement add test for a `--no-dev` build

---

.travis.yml
composer.json
phpunit.xml.dist

See silverstripe/silverstripe-framework#7653
Requires:

API Increase minimum PHP version to 7.1, include PHPUnit 7

---

composer.json

Parent issue https://github.com/silverstripeltd/open-sourcerers/issues/31

Install recipe-cms 5.x-dev on master branch.

---

.editorconfig
.travis.yml
composer.json
phpcs.xml.dist
phpunit.xml.dist

See https://github.com/silverstripe/silverstripe-framework/pull/8271 for info on
the specific PHPUnit version (temporary)
Hopefully this should get the tests green

Use PHPUnit 7.1.3, update PHPUnit config file schema, quote testsuites in Travis config

---

.travis.yml
composer.json

See https://github.com/silverstripe/silverstripe-framework/issues/8556

API Bump minimum PHP version to 7.1

---

.env.example

Addresses https://github.com/silverstripe/silverstripe-framework/issues/8598
Related: https://github.com/silverstripe/silverstripe-framework/pull/9052

NEW: Change .env.example to default to MySQL native driver

---

.travis.yml

Trusty to Xenial upgrade for a reference

Enhancement / Update travis config to use Xenial

---

phpunit.xml.dist

Change the path since mysite isn't used anymore, new sites have an app folder instead.

Update the default location for tests in a project

---

.cow.json

See https://github.com/silverstripe/silverstripe-framework/issues/9232
See https://github.com/silverstripe/silverstripe-installer/pull/260 for equivalent 4.x PR

Remove cow archive metadata

---

composer.json

See https://github.com/silverstripe/recipe-cms/issues/26

NEW Add silverstripe/login-forms

---

composer.json

Login forms should be treated as a core module. We should be doing new releases of login forms along with our quarterly releases.

BUG Treat login-forms as a core module

---

.travis.yml
behat.yml
composer.json

As part of https://github.com/silverstripe/silverstripe-framework/issues/9704

MNT Add PHP 8 builds

---

.travis.yml

Issue https://github.com/silverstripe/silverstripe-installer/issues/296
Other travis failures are unrelated
- multi tab validation on admin - https://travis-ci.com/github/silverstripe/silverstripe-installer/jobs/500590488
- change sort order + manage files on asset admin - https://travis-ci.com/github/silverstripe/silverstripe-installer/jobs/500590490

MNT Install vfsstream on travis

---

app/_config/email.yml

Issue https://github.com/silverstripe/silverstripe-installer/issues/307

ENH Use Swift_SendmailTransport for new projects

---

.cow.json

- Fixes https://github.com/silverstripeltd/product-issues/issues/466

MNT supress changelog generation and loosen dependency constraint

---

.travis.yml
composer.json

Issue https://github.com/silverstripeltd/product-issues/issues/492

DEP 4.10 requirements

---

.travis.yml

Issue https://github.com/silverstripe/silverstripe-framework/issues/10294

MNT Do not allow failures on php 8.1

---

.github/workflows/ci.yml

Issue https://github.com/silverstripe/gha-ci/issues/37

MNT Fix typos
